spring.application.name=sb-ecom

project.image=images/

spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookieName=springBootEcom

#STRIPE KEY
stripe.secret.key=${STRIPE_SECRET_KEY}